import pathlib
import typing

class Decoder:
    def __init__(self, path: pathlib.Path | str | bytes) -> None: ...
    def id_to_stream(self) -> dict[int, dict[str, typing.Any]]: ...
    def __iter__(self) -> Decoder: ...
    def __next__(self) -> dict[str, typing.Any]: ...
